version: '2'

services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: on-failure

  celery:
    build: .
    container_name: celery
    command: celery -A mini_blog worker -l info
    depends_on:
      - rabbitmq
    restart: on-failure

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    command: gunicorn mini_blog.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - celery
    restart: on-failure
